### ISSUE TITLE
OOP cheat sheet

### ISSUE THREAD

**Issue by ngsanthosh** [Suryansh1720001/Developer-Cheatsheet#110]
I am about to add Object Oriented Programming Cheat sheet. Kindly assign it to me :)

**Comment by Suryansh1720001** [comment]
Hello @ngsanthosh 
Go for it. And go through the readme and contributing file first before sending the pull request. 
Follow @Suryansh1720001 and Star the repo ⭐
( Also please keep this in mind - don't send any Plagiarized content )
Thank you
