### ISSUE TITLE
Updating readme.md

### ISSUE THREAD

**Issue by ayushtiwari110** [Suryansh1720001/Developer-Cheatsheet#20]
Can I update readme file with a contributing guide section and some badges? 
Kindly tell, and if yes , add hacktoberfest tag in this issue.

**Comment by Suryansh1720001** [comment]
Hello @ayushtiwari110 
Go for it. And go through the readme and contributing file first before sending the pull request.
Thank you

**Comment by ayushtiwari110** [comment]
hello @Suryansh1720001 I have made a pull request regarding changes to readme file which I have done. Kindly have a look
