### ISSUE TITLE
Adding java cheatsheet 

### ISSUE THREAD

**Issue by subratkumar46** [Suryansh1720001/Developer-Cheatsheet#41]
I want to add JAVA cheatsheet . Please assign it to me .

**Comment by Suryansh1720001** [comment]
Hello @subratkumar46 
Go for it. And go through the readme and contributing file first before sending the pull request.
Thank you

**Comment by subratkumar46** [comment]
Thanks @Suryansh1720001 for the oppourtunity .
After going through all your contributing giuidelines  I have made the JAVA CHEATSHEET #50  .
I hope this will be helpful for the community .

**Comment by Sparsh011** [comment]
Hey, can I contribute to the Java cheatsheet?
