### ISSUE TITLE
C++ Cheatsheet

### ISSUE THREAD

**Issue by faria-karim-porna** [Suryansh1720001/Developer-Cheatsheet#76]
Hey @Suryansh1720001 I want to add a c++ cheatsheet to this repository. Can u assign me this issue under the hacktoberfest label?

**Comment by Suryansh1720001** [comment]
Hello @faria-karim-porna 
Go for it. And go through the readme and contributing file first before sending the pull request.
( Also please keep this in mind - don't send any Plagiarized content )
Thank you

**Comment by amanaggarwal06** [comment]
Hey, please assign it to me.
I want to contribute.

**Comment by Suryansh1720001** [comment]
Close as complete #116
