### ISSUE TITLE
Fix the "hacktoberfest" tag of the repo

### ISSUE THREAD

**Issue by Anirban-Chand** [Suryansh1720001/Developer-Cheatsheet#8]
It is spelled as "hactoberfest" in the repo tags, so on hacktoberfest.com it is showing that this repo is not participating in hacktoberfest 2022. Please fix this asap @Suryansh1720001 & @ANSHUMANDAS1506

**Comment by Suryansh1720001** [comment]
Thank you for informing me about this. 
Can you please check for this now?

**Comment by Anirban-Chand** [comment]
> Thank you for informing me about this. Can you please check for this now?

Yes, it's alright now.
